// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Yomogi } from "next/font/google";
import { CartProvider } from "@/contexts/CartContext";
import Cart from "@/components/Cart";
import { Hachi_Maru_Pop } from "next/font/google";
import { Rampart_One } from "next/font/google";
import { Yuji_Mai } from "next/font/google";
const mainFont = Yomogi({
  weight: ["400"],
  subsets: ["latin"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" data-theme="retro">
      <body className={`${mainFont.className}`}>
        <CartProvider>
          {children}
          <Cart />
        </CartProvider>
      </body>
    </html>
  );
}
